// Generated changelog data
// Update this file when releasing a new version
// User descriptions are auto-generated by scripts/generate-user-descriptions.ts

import type { ChangelogVersion } from './changelog'

export const CURRENT_VERSION = '0.2.2'

export const changelogVersions: ChangelogVersion[] = [
    {
      version: '0.2.2',
      date: '2026-01-03',
      changes: [
        {
          type: 'feature',
          scope: 'bezpecnost',
          description: 'Přidána autentizace na všechny admin API endpointy',
          userDescription: 'Všechny administrátorské funkce jsou nyní chráněny přihlášením pro vyšší bezpečnost.'
        },
        {
          type: 'feature',
          scope: 'pdf',
          description: 'Browser pooling pro rychlejší generování PDF',
          userDescription: 'PDF dokumenty se nyní generují výrazně rychleji díky optimalizaci na pozadí.'
        },
        {
          type: 'fix',
          scope: 'objednavky',
          description: 'Oprava validace datumových polí při ukládání objednávky',
          userDescription: 'Opravili jsme chybu, kdy nešlo uložit objednávku s vyplněnými daty.'
        },
        {
          type: 'fix',
          scope: 'ui',
          description: 'Oprava výšky postranního menu v administraci',
          userDescription: 'Postranní menu v administraci se nyní správně zobrazuje na celou výšku obrazovky.'
        }
      ]
    },
    {
      version: '0.2.1',
      date: '2026-01-02',
      changes: [
        {
          type: 'feature',
          scope: 'produkty',
          description: 'Rozšířená pole produktů (dodavatel, nákupní cena, marže)',
          userDescription: 'U produktů nyní evidujete dodavatele, nákupní cenu a marži pro lepší přehled o nákladech.'
        },
        {
          type: 'feature',
          scope: 'produkty',
          description: 'Vylepšená synchronizace s Pipedrive',
          userDescription: 'Produkty se nyní synchronizují z Pipedrive přesněji včetně všech důležitých údajů.'
        },
        {
          type: 'feature',
          scope: 'objednavky',
          description: 'Nový design tiskové verze objednávky',
          userDescription: 'Tisková verze objednávky má nový, přehlednější vzhled.'
        },
        {
          type: 'feature',
          scope: 'produkty',
          description: 'Nové kategorie produktů (zastřešení, doprava, služby)',
          userDescription: 'Produkty lze nyní třídit do nových kategorií jako zastřešení, doprava nebo služby.'
        },
        {
          type: 'fix',
          scope: 'dokumentace',
          description: 'Aktualizace CLAUDE.md dokumentace',
          userDescription: 'Aktualizovali jsme interní dokumentaci projektu.'
        }
      ]
    },
    {
      version: '0.2.0',
      date: '2026-01-01',
      changes: [
        {
          type: 'feature',
          scope: 'novinky',
          description: 'Sekce Novinky v admin panelu s přehledem změn v aplikaci',
          userDescription: 'Prohlédněte si přehledně všechny novinky a změny v aplikaci v nové sekci Novinky.'
        },
        {
          type: 'feature',
          scope: 'changelog',
          description: 'Automatický překlad technických popisů do srozumitelné češtiny pomocí AI',
          userDescription: 'Čtěte popisy změn v aplikaci v jednoduché češtině místo složitých technických pojmů.'
        },
        {
          type: 'fix',
          scope: 'pdf',
          description: 'Stabilizace generování PDF na Railway (retry logika, pipe mód)',
          userDescription: 'Opravili jsme problémy s vytvářením PDF souborů, které se nyní generují spolehlivěji.'
        },
        {
          type: 'fix',
          scope: 'pdf',
          description: 'Použití Nix Chromium pro Puppeteer na Railway',
          userDescription: 'Vylepšili jsme technické zázemí pro rychlejší a stabilnější vytváření PDF dokumentů.'
        }
      ]
    },
    {
      version: '0.1.0',
      date: '2025-12-30',
      changes: [
        {
          type: 'feature',
          scope: 'nabidky',
          description: 'Drag & drop řazení položek v editoru nabídek',
          userDescription: 'Položky v nabídce můžete nyní snadno přesouvat pouhým přetažením myší.'
        },
        {
          type: 'feature',
          scope: 'nabidky',
          description: 'Nové produkty se přidávají na začátek seznamu',
          userDescription: 'Nově přidané produkty se zobrazují na začátku seznamu pro rychlejší přístup.'
        },
        {
          type: 'feature',
          scope: 'ui',
          description: 'Vylepšený katalog produktů s tlačítkem + a hover efektem',
          userDescription: 'Procházení produktů je nyní pohodlnější díky vylepšenému vzhledu a snadnému přidávání tlačítkem.'
        },
        {
          type: 'feature',
          scope: 'konfigurace',
          description: '11-krokový konfigurátor bazénů',
          userDescription: 'Vytvořte nabídku bazénu snadno pomocí průvodce v 11 krocích.'
        },
        {
          type: 'feature',
          scope: 'nabidky',
          description: 'Systém variant nabídek (Ekonomická, Optimální, Prémiová)',
          userDescription: 'Vytvářejte tři různé varianty nabídky najednou podle cenové úrovně.'
        },
        {
          type: 'feature',
          scope: 'objednavky',
          description: 'Konverze nabídek na objednávky',
          userDescription: 'Schválenou nabídku můžete jedním kliknutím převést na objednávku.'
        },
        {
          type: 'feature',
          scope: 'vyroba',
          description: 'Sledování výroby s checklistem',
          userDescription: 'Sledujte průběh výroby pomocí přehledného seznamu úkolů.'
        },
        {
          type: 'feature',
          scope: 'produkty',
          description: 'Synchronizace produktů z Pipedrive',
          userDescription: 'Produkty se nyní automaticky aktualizují z vašeho CRM systému.'
        },
        {
          type: 'feature',
          scope: 'auth',
          description: 'Přihlašování a správa uživatelů',
          userDescription: 'Přidali jsme zabezpečené přihlašování a správu uživatelských účtů.'
        },
        {
          type: 'fix',
          scope: 'nabidky',
          description: 'Oprava načítání položek při editaci existující nabídky',
          userDescription: 'Opravili jsme chybu, kdy se při úpravě nabídky nezobrazovaly její položky.'
        }
      ]
    }
  ]
