// Generated changelog data
// Update this file when releasing a new version
// User descriptions are auto-generated by scripts/generate-user-descriptions.ts

import type { ChangelogVersion } from './changelog'

export const CURRENT_VERSION = '0.1.0'

export const changelogVersions: ChangelogVersion[] = [
    {
      version: '0.1.0',
      date: '2025-01-01',
      changes: [
        {
          type: 'feature',
          scope: 'nabidky',
          description: 'Drag & drop řazení položek v editoru nabídek',
          userDescription: 'Položky v nabídce můžete nyní snadno přesouvat pouhým přetažením myší.'
        },
        {
          type: 'feature',
          scope: 'nabidky',
          description: 'Nové produkty se přidávají na začátek seznamu',
          userDescription: 'Nově přidané produkty se zobrazují na začátku seznamu pro rychlejší přístup.'
        },
        {
          type: 'feature',
          scope: 'ui',
          description: 'Vylepšený katalog produktů s tlačítkem "+" a hover efektem',
          userDescription: 'Procházení produktů je nyní pohodlnější díky vylepšenému vzhledu a snadnému přidávání tlačítkem.'
        },
        {
          type: 'feature',
          scope: 'konfigurace',
          description: '11-krokový konfigurátor bazénů',
          userDescription: 'Vytvořte nabídku bazénu snadno pomocí průvodce v 11 krocích.'
        },
        {
          type: 'feature',
          scope: 'nabidky',
          description: 'Systém variant nabídek (Ekonomická, Optimální, Prémiová)',
          userDescription: 'Vytvářejte tři různé varianty nabídky najednou podle cenové úrovně.'
        },
        {
          type: 'feature',
          scope: 'objednavky',
          description: 'Konverze nabídek na objednávky',
          userDescription: 'Schválenou nabídku můžete jedním kliknutím převést na objednávku.'
        },
        {
          type: 'feature',
          scope: 'vyroba',
          description: 'Sledování výroby s checklistem',
          userDescription: 'Sledujte průběh výroby pomocí přehledného seznamu úkolů.'
        },
        {
          type: 'feature',
          scope: 'produkty',
          description: 'Synchronizace produktů z Pipedrive',
          userDescription: 'Produkty se nyní automaticky aktualizují z vašeho CRM systému.'
        },
        {
          type: 'feature',
          scope: 'auth',
          description: 'Přihlašování a správa uživatelů',
          userDescription: 'Přidali jsme zabezpečené přihlašování a správu uživatelských účtů.'
        },
        {
          type: 'fix',
          scope: 'nabidky',
          description: 'Oprava načítání položek při editaci existující nabídky',
          userDescription: 'Opravili jsme chybu, kdy se při úpravě nabídky nezobrazovaly její položky.'
        }
      ]
    }
  ]
