// Generated changelog data
// Update this file when releasing a new version
// User descriptions are auto-generated by scripts/generate-user-descriptions.ts

import type { ChangelogVersion } from './changelog'

export const CURRENT_VERSION = '0.5.1'

export const changelogVersions: ChangelogVersion[] = [
    {
      version: '0.5.1',
      date: '2026-02-10',
      time: '12:00',
      changes: [
        {
          type: 'feature',
          scope: 'pdf',
          description: 'Číslování stránek v PDF nabídkách a objednávkách',
          userDescription: 'PDF nabídky i objednávky nyní obsahují číslování stránek ve formátu „Strana 2 z 8" v pravém dolním rohu. Titulní strana zůstává bez čísla.'
        },
        {
          type: 'feature',
          scope: 'objednavky',
          description: 'Popis položek v PDF objednávky (stejně jako v nabídce)',
          userDescription: 'V PDF objednávky se u položek nyní zobrazuje popis produktu — stejně jako v nabídce. Díky tomu zákazník lépe vidí, co přesně objednává.'
        },
        {
          type: 'fix',
          scope: 'nabidky',
          description: 'Oprava textu u 2. důvodu v sekci „7 důvodů pro Rentmil"',
          userDescription: 'Upraven text u prémiového materiálu Polystone P — nově „životnost 20 let" místo původní formulace.'
        }
      ]
    },
    {
      version: '0.5.0',
      date: '2026-02-07',
      time: '00:30',
      changes: [
        {
          type: 'feature',
          scope: 'nabidky',
          description: 'Oslovení zákazníka v českém vokativu (5. pádu) v PDF nabídce',
          userDescription: 'PDF nabídky nyní oslovují zákazníka správně česky — „Vážený pane Nováku" nebo „Vážená paní Nováková". Oslovení se generuje automaticky z jména a můžete ho kdykoliv ručně upravit v editoru nabídky.'
        },
        {
          type: 'feature',
          scope: 'nabidky',
          description: 'Úvodní dopis jednatele v PDF nabídce (IntroPage)',
          userDescription: 'PDF nabídky obsahují novou druhou stranu s osobním dopisem od jednatele Rentmil. Text dopisu se automaticky přizpůsobí pohlaví zákazníka.'
        },
        {
          type: 'feature',
          scope: 'nabidky',
          description: 'Sezónní dostupnost a urgency banner v editoru nabídek',
          userDescription: 'V editoru nabídek najdete novou sekci „Sezónní dostupnost" — zadejte termín objednání, dodání, měsíc kapacity a počet volných montáží. Tyto údaje se zobrazí jako urgency banner v PDF nabídce.'
        },
        {
          type: 'feature',
          scope: 'nabidky',
          description: 'Redesign PDF nabídky: titulní strana, 7 důvodů pro Rentmil, další kroky',
          userDescription: 'PDF nabídky mají zcela nový design — efektní titulní strana s fotografií bazénu, stránka „7 důvodů pro Rentmil" s obchodními podmínkami, stránka s recenzemi zákazníků, časovou osou realizace a kontaktem na obchodníka.'
        },
        {
          type: 'feature',
          scope: 'nabidky',
          description: 'Vyhledávání produktů přes combobox s fulltextovým hledáním',
          userDescription: 'Při přidávání produktu do nabídky můžete nyní vyhledávat přes combobox s fulltextovým hledáním podle názvu i kódu produktu.'
        },
        {
          type: 'feature',
          scope: 'integrace',
          description: 'Napojení na Pipedrive custom field "oslovení" pro persony',
          userDescription: 'Systém je připraven na načítání oslovení zákazníka přímo z Pipedrive CRM, pokud je tam zadáno.'
        },
        {
          type: 'fix',
          scope: 'pdf',
          description: 'Zarovnání hvězdiček Google hodnocení v PDF nabídce',
          userDescription: 'Opraveno zarovnání hvězdiček v sekci Google hodnocení — půlhvězdička je nyní ve stejné rovině jako ostatní.'
        }
      ]
    },
    {
      version: '0.4.0',
      date: '2026-02-06',
      time: '15:00',
      changes: [
        {
          type: 'feature',
          scope: 'objednavky',
          description: 'PDF objednávky jako plná kupní smlouva s 13 právními články',
          userDescription: 'PDF objednávky nyní slouží jako plná kupní smlouva. Obsahuje 13 smluvních článků (předmět smlouvy, platební podmínky, termíny, doprava, záruky a další), stránku s podpisy včetně razítka a nákres pro umístění schodiště.'
        },
        {
          type: 'feature',
          scope: 'objednavky',
          description: 'Nová pole objednávky: místo plnění, stavební připravenost, způsob dopravy, DPH, hmotnost',
          userDescription: 'V editoru objednávky najdete nová pole pro smluvní údaje: adresu místa plnění, datum stavební připravenosti, předpokládané dodání, způsob a náklady dopravy, hmotnost zásilky a sazbu DPH. Vše se automaticky propíše do PDF smlouvy.'
        },
        {
          type: 'feature',
          scope: 'produkty',
          description: 'Setové doplňky (set addons) u produktů kategorie "sety"',
          userDescription: 'U bazénových setů nyní můžete definovat volitelné doplňky (např. protiproud, osvětlení). Při přidání setu do nabídky si vyberete, které doplňky zákazník chce - každý se přidá jako samostatná položka.'
        },
        {
          type: 'feature',
          scope: 'nabidky',
          description: 'Setové doplňky v editoru nabídek s parent-child vazbou',
          userDescription: 'Při přidání bazénového setu do nabídky se zobrazí dialog s výběrem doplňků. Vybrané doplňky se přidají jako podřazené položky setu a můžete je kdykoliv přidat nebo odebrat.'
        },
        {
          type: 'fix',
          scope: 'objednavky',
          description: 'Konverze nabídky na objednávku přenáší nová smluvní pole',
          userDescription: 'Při převodu nabídky na objednávku se nyní správně přenesou všechny údaje potřebné pro smluvní dokumentaci.'
        }
      ]
    },
    {
      version: '0.3.2',
      date: '2026-01-27',
      time: '22:00',
      changes: [
        {
          type: 'feature',
          scope: 'nabidky',
          description: 'Sbalitelné kategorie v katalogu produktů s počtem položek',
          userDescription: 'Katalog produktů v editoru nabídek má nyní sbalitelné kategorie. Kliknutím na kategorii ji rozbalíte nebo sbalíte. U každé kategorie vidíte počet produktů.'
        },
        {
          type: 'feature',
          scope: 'nabidky',
          description: 'Tlačítka Rozbalit/Sbalit vše pro hromadné ovládání kategorií',
          userDescription: 'V záhlaví katalogu produktů jsou nová tlačítka pro rychlé rozbalení nebo sbalení všech kategorií najednou.'
        },
        {
          type: 'feature',
          scope: 'nabidky',
          description: 'Plovoucí sidebar s katalogem produktů (sticky)',
          userDescription: 'Katalog produktů je nyní plovoucí - zůstává viditelný při scrollování stránkou, takže máte produkty vždy po ruce.'
        },
        {
          type: 'feature',
          scope: 'nabidky',
          description: 'Vyhledávání produktů podle názvu i kódu s normalizací rozměrů',
          userDescription: 'Hledání v katalogu produktů nyní funguje i podle kódu produktu. Navíc můžete hledat rozměry pomocí "x" i "×" - např. "7x3" najde bazény 7×3m.'
        },
        {
          type: 'fix',
          scope: 'nabidky',
          description: 'Zobrazení celého názvu produktu včetně rozměrů',
          userDescription: 'V katalogu produktů se nyní zobrazuje celý název produktu včetně rozměrů bazénu, které jsou zásadní pro správný výběr.'
        }
      ]
    },
    {
      version: '0.3.1',
      date: '2026-01-27',
      time: '20:00',
      changes: [
        {
          type: 'fix',
          scope: 'ceny',
          description: 'Oprava výpočtu cen pro řetězené procentuální příplatky (A→B→C)',
          userDescription: 'Opravili jsme výpočet cen, kdy procentuální příplatek závisí na jiném procentuálním příplatku. Nyní se ceny počítají správně i pro složité závislosti.'
        },
        {
          type: 'fix',
          scope: 'nabidky',
          description: 'Oprava rekurzivního přidávání povinných příplatků',
          userDescription: 'Pokud příplatek A vyžaduje příplatek B, oba se nyní správně přidají do nabídky automaticky.'
        },
        {
          type: 'fix',
          scope: 'produkty',
          description: 'Atomická aktualizace položek ve skupinách produktů (transakce)',
          userDescription: 'Úprava skupin produktů je nyní bezpečnější - změny se buď uloží celé, nebo vůbec.'
        },
        {
          type: 'fix',
          scope: 'produkty',
          description: 'Oprava ukládání důvodu změny při hromadném přeceňování',
          userDescription: 'Při hromadné změně cen se nyní správně ukládá důvod změny do historie.'
        },
        {
          type: 'fix',
          scope: 'integrace',
          description: 'Přidána retry logika pro synchronizaci produktů z Pipedrive',
          userDescription: 'Synchronizace produktů z Pipedrive je nyní odolnější vůči dočasným výpadkům sítě.'
        },
        {
          type: 'fix',
          scope: 'bezpecnost',
          description: 'Oprava autentizace API klíčem pro sync endpoint',
          userDescription: 'Zpřísnili jsme zabezpečení synchronizačního endpointu.'
        },
        {
          type: 'fix',
          scope: 'nabidky',
          description: 'Podpora starých kategorií produktů (bazeny, prislusenstvi) s automatickým převodem',
          userDescription: 'Nabídky se starými kategoriemi produktů nyní fungují správně - automaticky se převádí na nové kategorie.'
        }
      ]
    },
    {
      version: '0.3.0',
      date: '2026-01-27',
      time: '12:30',
      changes: [
        {
          type: 'feature',
          scope: 'produkty',
          description: 'Nový systém správy produktů s CRUD operacemi přímo v aplikaci',
          userDescription: 'Produkty nyní můžete vytvářet, upravovat a mazat přímo v aplikaci bez nutnosti synchronizace z Pipedrive.'
        },
        {
          type: 'feature',
          scope: 'produkty',
          description: 'Koeficientové ceny s volbou jednotky (m² povrch nebo bm obvod)',
          userDescription: 'Pro příplatky jako 8mm tloušťka nebo lemová trubka lze nastavit cenu podle povrchu bazénu (m²) nebo jeho obvodu (bm).'
        },
        {
          type: 'feature',
          scope: 'produkty',
          description: 'Procentuální příplatky počítané z referenčního produktu',
          userDescription: 'Příplatky jako "ostré rohy" lze nastavit jako procento z ceny jiného produktu (např. 10% z bazénového skeletu).'
        },
        {
          type: 'feature',
          scope: 'produkty',
          description: 'Skupiny produktů (balíčky) pro rychlé vkládání do nabídek',
          userDescription: 'Vytvořte si předpřipravené skupiny produktů a vkládejte je do nabídek jedním kliknutím.'
        },
        {
          type: 'feature',
          scope: 'produkty',
          description: 'Hromadné přeceňování produktů (procentuální nebo fixní změna)',
          userDescription: 'Změňte ceny více produktů najednou - zadejte procento nebo fixní částku a změna se aplikuje na vybrané produkty.'
        },
        {
          type: 'feature',
          scope: 'produkty',
          description: 'CSV import cen produktů',
          userDescription: 'Importujte ceny z CSV souboru ve formátu kód;cena pro rychlou aktualizaci ceníku.'
        },
        {
          type: 'feature',
          scope: 'produkty',
          description: 'Nové kategorie produktů: skelety, sety, příplatky, zateplení, vysavače',
          userDescription: 'Produkty jsou nyní přehledněji organizovány do nových kategorií odpovídajících katalogu Rentmil.'
        },
        {
          type: 'feature',
          scope: 'produkty',
          description: 'Import 290 produktů z CSV katalogů (skelety, sety, doplňky)',
          userDescription: 'Do aplikace bylo naimportováno 290 produktů včetně bazénových skeletů, setů a veškerého příslušenství.'
        }
      ]
    },
    {
      version: '0.2.7',
      date: '2026-01-20',
      time: '12:00',
      changes: [
        {
          type: 'feature',
          scope: 'pdf',
          description: 'Volba kvality PDF - dropdown menu pro email (menší soubor) a tisk (vysoká kvalita)',
          userDescription: 'Při stahování PDF dokumentu nyní můžete vybrat kvalitu: "Pro email" (optimalizovaná velikost) nebo "Pro tisk" (plná kvalita obrázků).'
        },
        {
          type: 'fix',
          scope: 'pdf',
          description: 'Aktualizace loga na oranžový gradient',
          userDescription: 'PDF dokumenty nyní obsahují aktuální logo Rentmil v oranžovém gradientu.'
        }
      ]
    },
    {
      version: '0.2.6',
      date: '2026-01-07',
      time: '15:00',
      changes: [
        {
          type: 'feature',
          scope: 'konfigurator',
          description: 'Předvybrané nejoblíbenější varianty ve všech krocích',
          userDescription: 'Konfigurátor nyní automaticky předvybírá nejoblíbenější volby v každém kroku, což urychluje proces konfigurace.'
        },
        {
          type: 'feature',
          scope: 'konfigurator',
          description: 'Souhrn konfigurace zobrazuje pouze potvrzené kroky',
          userDescription: 'V pravém panelu se nyní zobrazují pouze kroky, které jste potvrdili kliknutím na "Další krok".'
        },
        {
          type: 'feature',
          scope: 'konfigurator',
          description: 'Obrázky schodišť podle tvaru bazénu (zaoblené/ostré rohy)',
          userDescription: 'Při výběru schodiště vidíte obrázky odpovídající tvaru vašeho bazénu.'
        },
        {
          type: 'feature',
          scope: 'konfigurator',
          description: 'Rozlišení duplicitní konfigurace na Thank You stránce',
          userDescription: 'Pokud odešlete stejnou konfiguraci vícekrát, uvidíte upozornění s výzvou ke kontrole emailu.'
        },
        {
          type: 'fix',
          scope: 'konfigurator',
          description: 'Checkbox výběru viditelný nad obrázkem schodiště',
          userDescription: 'Opravena viditelnost zaškrtávacího políčka u výběru schodiště.'
        },
        {
          type: 'feature',
          scope: 'email',
          description: 'Nový předmět emailu: "Bazény Rentmil - Gratulujeme! O krok blíže vysněnému bazénu"',
          userDescription: 'Potvrzovací email má nový přívětivější předmět.'
        },
        {
          type: 'fix',
          scope: 'admin',
          description: 'Oprava oprávnění pro uživatele s rolí "user" - PDF export, změna stavu nabídek, práce s objednávkami a výrobou',
          userDescription: 'Uživatelé s rolí "user" nyní mohou exportovat PDF, měnit stavy nabídek a pracovat s objednávkami a výrobou.'
        }
      ]
    },
    {
      version: '0.2.5',
      date: '2026-01-06',
      time: '14:10',
      changes: [
        {
          type: 'feature',
          scope: 'konfigurator',
          description: 'Nový design Thank You stránky s maskotem a timeline',
          userDescription: 'Po odeslání konfigurace vás přivítá náš maskot "Bazénový mistr" s přehledem dalších kroků.'
        },
        {
          type: 'feature',
          scope: 'konfigurator',
          description: 'CTA na blog "Jak vybrat bazén" na Thank You stránce',
          userDescription: 'Na stránce po odeslání najdete odkaz na naše poradenské články pro výběr bazénu.'
        },
        {
          type: 'feature',
          scope: 'email',
          description: 'Kontaktní údaje zákazníka v potvrzovacím emailu',
          userDescription: 'V potvrzovacím emailu nyní vidíte i své kontaktní údaje pro kontrolu.'
        },
        {
          type: 'feature',
          scope: 'email',
          description: 'Informace o zastřešení v potvrzovacím emailu',
          userDescription: 'Email s konfigurací nyní obsahuje i informaci o zvoleném zastřešení.'
        },
        {
          type: 'fix',
          scope: 'email',
          description: 'Aktualizace "23 let" na "24 let zkušeností"',
          userDescription: 'Aktualizovali jsme počet let zkušeností v patičce emailu.'
        }
      ]
    },
    {
      version: '0.2.4',
      date: '2026-01-06',
      time: '14:00',
      changes: [
        {
          type: 'feature',
          scope: 'konfigurator',
          description: 'Kompletní UX a obsahové vylepšení všech kroků konfigurátoru',
          userDescription: 'Konfigurátor bazénů prošel kompletní revizí - nové přehlednější grafiky, aktualizované texty a vylepšená navigace.'
        },
        {
          type: 'feature',
          scope: 'konfigurator',
          description: 'Nový pohled shora (půdorys) pro výběr typu bazénu',
          userDescription: 'Ve výběru typu bazénu vidíte nyní bazén z ptačí perspektivy pro lepší představu o skimmeru a přelivovém žlabu.'
        },
        {
          type: 'feature',
          scope: 'konfigurator',
          description: 'Kruhové bazény - zjednodušený průchod bez zastřešení a protiproudu',
          userDescription: 'Pro kruhové bazény jsme zjednodušili konfiguraci - přeskakují se kroky, které pro ně nejsou relevantní.'
        },
        {
          type: 'fix',
          scope: 'konfigurator',
          description: 'Aktualizované tipy pro rozměry bazénů',
          userDescription: 'Tipy pro výběr rozměrů byly aktualizovány podle nejčastějších požadavků zákazníků.'
        },
        {
          type: 'feature',
          scope: 'konfigurator',
          description: 'Odkaz na ochranu osobních údajů v kontaktním formuláři',
          userDescription: 'V kontaktním formuláři je nyní odkaz na zásady ochrany osobních údajů dle GDPR.'
        }
      ]
    },
    {
      version: '0.2.3',
      date: '2026-01-03',
      time: '01:15',
      changes: [
        {
          type: 'feature',
          scope: 'nabidky',
          description: 'Editovatelný termín dodání v nabídce',
          userDescription: 'V editoru nabídky lze nyní upravit termín dodání, který se zobrazí v PDF dokumentu.'
        },
        {
          type: 'fix',
          scope: 'objednavky',
          description: 'Odstranění pevného textu "50%" u zálohy v PDF objednávky',
          userDescription: 'V PDF objednávky se u zálohy už nezobrazuje pevný text "50%" - zobrazí se pouze částka.'
        }
      ]
    },
    {
      version: '0.2.2',
      date: '2026-01-03',
      time: '00:30',
      changes: [
        {
          type: 'feature',
          scope: 'bezpecnost',
          description: 'Přidána autentizace na všechny admin API endpointy',
          userDescription: 'Všechny administrátorské funkce jsou nyní chráněny přihlášením pro vyšší bezpečnost.'
        },
        {
          type: 'feature',
          scope: 'pdf',
          description: 'Browser pooling pro rychlejší generování PDF',
          userDescription: 'PDF dokumenty se nyní generují výrazně rychleji díky optimalizaci na pozadí.'
        },
        {
          type: 'fix',
          scope: 'objednavky',
          description: 'Oprava validace datumových polí při ukládání objednávky',
          userDescription: 'Opravili jsme chybu, kdy nešlo uložit objednávku s vyplněnými daty.'
        },
        {
          type: 'fix',
          scope: 'ui',
          description: 'Oprava výšky postranního menu v administraci',
          userDescription: 'Postranní menu v administraci se nyní správně zobrazuje na celou výšku obrazovky.'
        }
      ]
    },
    {
      version: '0.2.1',
      date: '2026-01-02',
      time: '20:45',
      changes: [
        {
          type: 'feature',
          scope: 'produkty',
          description: 'Rozšířená pole produktů (dodavatel, nákupní cena, marže)',
          userDescription: 'U produktů nyní evidujete dodavatele, nákupní cenu a marži pro lepší přehled o nákladech.'
        },
        {
          type: 'feature',
          scope: 'produkty',
          description: 'Vylepšená synchronizace s Pipedrive',
          userDescription: 'Produkty se nyní synchronizují z Pipedrive přesněji včetně všech důležitých údajů.'
        },
        {
          type: 'feature',
          scope: 'objednavky',
          description: 'Nový design tiskové verze objednávky',
          userDescription: 'Tisková verze objednávky má nový, přehlednější vzhled.'
        },
        {
          type: 'feature',
          scope: 'produkty',
          description: 'Nové kategorie produktů (zastřešení, doprava, služby)',
          userDescription: 'Produkty lze nyní třídit do nových kategorií jako zastřešení, doprava nebo služby.'
        },
        {
          type: 'fix',
          scope: 'dokumentace',
          description: 'Aktualizace CLAUDE.md dokumentace',
          userDescription: 'Aktualizovali jsme interní dokumentaci projektu.'
        }
      ]
    },
    {
      version: '0.2.0',
      date: '2026-01-01',
      time: '15:00',
      changes: [
        {
          type: 'feature',
          scope: 'novinky',
          description: 'Sekce Novinky v admin panelu s přehledem změn v aplikaci',
          userDescription: 'Prohlédněte si přehledně všechny novinky a změny v aplikaci v nové sekci Novinky.'
        },
        {
          type: 'feature',
          scope: 'changelog',
          description: 'Automatický překlad technických popisů do srozumitelné češtiny pomocí AI',
          userDescription: 'Čtěte popisy změn v aplikaci v jednoduché češtině místo složitých technických pojmů.'
        },
        {
          type: 'fix',
          scope: 'pdf',
          description: 'Stabilizace generování PDF na Railway (retry logika, pipe mód)',
          userDescription: 'Opravili jsme problémy s vytvářením PDF souborů, které se nyní generují spolehlivěji.'
        },
        {
          type: 'fix',
          scope: 'pdf',
          description: 'Použití Nix Chromium pro Puppeteer na Railway',
          userDescription: 'Vylepšili jsme technické zázemí pro rychlejší a stabilnější vytváření PDF dokumentů.'
        }
      ]
    },
    {
      version: '0.1.0',
      date: '2025-12-30',
      time: '18:00',
      changes: [
        {
          type: 'feature',
          scope: 'nabidky',
          description: 'Drag & drop řazení položek v editoru nabídek',
          userDescription: 'Položky v nabídce můžete nyní snadno přesouvat pouhým přetažením myší.'
        },
        {
          type: 'feature',
          scope: 'nabidky',
          description: 'Nové produkty se přidávají na začátek seznamu',
          userDescription: 'Nově přidané produkty se zobrazují na začátku seznamu pro rychlejší přístup.'
        },
        {
          type: 'feature',
          scope: 'ui',
          description: 'Vylepšený katalog produktů s tlačítkem + a hover efektem',
          userDescription: 'Procházení produktů je nyní pohodlnější díky vylepšenému vzhledu a snadnému přidávání tlačítkem.'
        },
        {
          type: 'feature',
          scope: 'konfigurace',
          description: '11-krokový konfigurátor bazénů',
          userDescription: 'Vytvořte nabídku bazénu snadno pomocí průvodce v 11 krocích.'
        },
        {
          type: 'feature',
          scope: 'nabidky',
          description: 'Systém variant nabídek (Ekonomická, Optimální, Prémiová)',
          userDescription: 'Vytvářejte tři různé varianty nabídky najednou podle cenové úrovně.'
        },
        {
          type: 'feature',
          scope: 'objednavky',
          description: 'Konverze nabídek na objednávky',
          userDescription: 'Schválenou nabídku můžete jedním kliknutím převést na objednávku.'
        },
        {
          type: 'feature',
          scope: 'vyroba',
          description: 'Sledování výroby s checklistem',
          userDescription: 'Sledujte průběh výroby pomocí přehledného seznamu úkolů.'
        },
        {
          type: 'feature',
          scope: 'produkty',
          description: 'Synchronizace produktů z Pipedrive',
          userDescription: 'Produkty se nyní automaticky aktualizují z vašeho CRM systému.'
        },
        {
          type: 'feature',
          scope: 'auth',
          description: 'Přihlašování a správa uživatelů',
          userDescription: 'Přidali jsme zabezpečené přihlašování a správu uživatelských účtů.'
        },
        {
          type: 'fix',
          scope: 'nabidky',
          description: 'Oprava načítání položek při editaci existující nabídky',
          userDescription: 'Opravili jsme chybu, kdy se při úpravě nabídky nezobrazovaly její položky.'
        }
      ]
    }
  ]
