/**
 * Script to generate user-friendly descriptions for changelog entries
 * Uses Claude API to translate technical descriptions to plain Czech
 *
 * Usage: npx tsx scripts/generate-user-descriptions.ts
 *
 * Requires: ANTHROPIC_API_KEY environment variable (in .env.local or exported)
 */

import Anthropic from '@anthropic-ai/sdk'
import * as fs from 'fs'
import * as path from 'path'
import { config } from 'dotenv'

// Load environment variables from .env.local
config({ path: '.env.local' })

const CHANGELOG_DATA_PATH = path.join(
  process.cwd(),
  'src/lib/changelog-data.ts'
)

interface Change {
  type: 'feature' | 'fix' | 'improvement' | 'breaking'
  scope?: string
  description: string
  userDescription?: string
}

interface ChangelogVersion {
  version: string
  date: string
  changes: Change[]
}

// Extract changelog data from TypeScript file
function parseChangelogDataFile(content: string): ChangelogVersion[] {
  // Find the array content between changelogVersions: ChangelogVersion[] = [ and ]
  const match = content.match(
    /export const changelogVersions: ChangelogVersion\[\] = (\[[\s\S]*?\n\])/
  )
  if (!match) {
    throw new Error('Could not find changelogVersions in file')
  }

  // Parse the array - this is a simplified parser
  // We'll use eval in a safe way since we control the file
  const arrayContent = match[1]
  // eslint-disable-next-line no-eval
  const versions = eval(arrayContent)
  return versions
}

// Generate TypeScript code for the changelog data
function generateChangelogDataFile(
  versions: ChangelogVersion[],
  currentVersion: string
): string {
  const versionsJson = JSON.stringify(versions, null, 2)
    // Convert to TypeScript-friendly format
    .replace(/"type": "(\w+)"/g, "type: '$1'")
    .replace(/"scope": "([^"]+)"/g, "scope: '$1'")
    .replace(/"description": "([^"]+)"/g, "description: '$1'")
    .replace(/"userDescription": "([^"]+)"/g, "userDescription: '$1'")
    .replace(/"version": "([^"]+)"/g, "version: '$1'")
    .replace(/"date": "([^"]+)"/g, "date: '$1'")
    .replace(/"changes":/g, 'changes:')
    // Indent properly
    .split('\n')
    .map((line, i) => (i === 0 ? line : '  ' + line))
    .join('\n')

  return `// Generated changelog data
// Update this file when releasing a new version
// User descriptions are auto-generated by scripts/generate-user-descriptions.ts

import type { ChangelogVersion } from './changelog'

export const CURRENT_VERSION = '${currentVersion}'

export const changelogVersions: ChangelogVersion[] = ${versionsJson}
`
}

async function translateDescriptions(
  client: Anthropic,
  changes: Change[]
): Promise<Change[]> {
  // Filter changes that need translation
  const needsTranslation = changes.filter((c) => !c.userDescription)

  if (needsTranslation.length === 0) {
    console.log('  All changes already have user descriptions')
    return changes
  }

  console.log(`  Translating ${needsTranslation.length} descriptions...`)

  const prompt = `Jsi expert na psaní uživatelsky přívětivých textů pro české uživatele aplikace.

Přelož následující technické popisy změn v aplikaci do srozumitelné češtiny pro běžné uživatele, kteří nerozumí IT pojmům.

Pravidla:
- Piš jednoduše a srozumitelně
- Vysvětli, co změna znamená PRO UŽIVATELE (ne technicky)
- Použij běžná česká slova místo anglicismů
- Maximálně 1-2 věty
- Nepřidávej technické detaily
- Začni slovesem co uživatel může nově dělat nebo co se zlepšilo

Příklady:
- "Drag & drop řazení položek v editoru nabídek" → "Položky v nabídce můžete nyní snadno přesouvat pouhým přetažením myší."
- "Fix: quote items loading when editing" → "Opravili jsme chybu, kdy se při úpravě nabídky nezobrazovaly její položky."
- "Synchronizace produktů z Pipedrive" → "Produkty se nyní automaticky aktualizují z vašeho CRM systému."

Technické popisy k překladu (vrať JSON pole se stejným pořadím):
${JSON.stringify(
  needsTranslation.map((c) => ({
    type: c.type,
    scope: c.scope,
    description: c.description,
  })),
  null,
  2
)}

Odpověz POUZE JSON polem stringů s přeloženými popisy (bez markdown, bez vysvětlení):`

  const response = await client.messages.create({
    model: 'claude-sonnet-4-20250514',
    max_tokens: 2000,
    messages: [{ role: 'user', content: prompt }],
  })

  // Parse response
  const textContent = response.content.find((c) => c.type === 'text')
  if (!textContent || textContent.type !== 'text') {
    throw new Error('No text response from Claude')
  }

  let translations: string[]
  try {
    translations = JSON.parse(textContent.text)
  } catch {
    console.error('Failed to parse response:', textContent.text)
    throw new Error('Failed to parse Claude response as JSON')
  }

  if (translations.length !== needsTranslation.length) {
    throw new Error(
      `Expected ${needsTranslation.length} translations, got ${translations.length}`
    )
  }

  // Apply translations
  let translationIndex = 0
  return changes.map((change) => {
    if (!change.userDescription) {
      return {
        ...change,
        userDescription: translations[translationIndex++],
      }
    }
    return change
  })
}

async function main() {
  // Check for API key
  if (!process.env.ANTHROPIC_API_KEY) {
    console.error('Error: ANTHROPIC_API_KEY environment variable is required')
    console.error('Set it in .env.local or export it before running this script')
    process.exit(1)
  }

  console.log('Reading changelog data...')
  const fileContent = fs.readFileSync(CHANGELOG_DATA_PATH, 'utf-8')

  // Extract current version
  const versionMatch = fileContent.match(/CURRENT_VERSION = '([^']+)'/)
  const currentVersion = versionMatch ? versionMatch[1] : '0.1.0'

  // Parse existing data
  const versions = parseChangelogDataFile(fileContent)
  console.log(`Found ${versions.length} versions`)

  // Initialize Anthropic client
  const client = new Anthropic()

  // Process each version
  const updatedVersions: ChangelogVersion[] = []
  for (const version of versions) {
    console.log(`\nProcessing version ${version.version}...`)
    const updatedChanges = await translateDescriptions(client, version.changes)
    updatedVersions.push({
      ...version,
      changes: updatedChanges,
    })
  }

  // Generate updated file
  console.log('\nGenerating updated changelog-data.ts...')
  const newContent = generateChangelogDataFile(updatedVersions, currentVersion)
  fs.writeFileSync(CHANGELOG_DATA_PATH, newContent)

  console.log('Done! User descriptions have been generated.')
}

main().catch((error) => {
  console.error('Error:', error)
  process.exit(1)
})
